export const THEMES = [
  {
    id: "classic-warm",
    name: "Klasik Sıcak",
    desc: "Kahverengi, geleneksel mobilya",
    colors: ["#2C2420", "#C8553D", "#D4A03C", "#FAF8F5"],
    tags: ["Geleneksel", "Sıcak"],
    palette: {
      brand: "#2C2420",
      warm: "#FAF8F5",
      accent: "#C8553D",
      gold: "#D4A03C",
      text: "#2C2420",
      muted: "#6B5B4E",
      border: "#E8DDD0",
    },
  },
  {
    id: "navy-gold",
    name: "Navy Premium",
    desc: "Lacivert + altın, lüks düğün",
    colors: ["#1B2A4A", "#C9A55C", "#B8464B", "#FFFDF8"],
    tags: ["Premium", "Lüks"],
    palette: {
      brand: "#1B2A4A",
      warm: "#FFFDF8",
      accent: "#C9A55C",
      gold: "#C9A55C",
      text: "#1B2A4A",
      muted: "#7A7062",
      border: "#E5DDD0",
    },
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    desc: "Siyah-beyaz, temiz şık",
    colors: ["#111", "#FF4D4D", "#333", "#FAFAFA"],
    tags: ["Modern", "Minimal"],
    palette: {
      brand: "#111",
      warm: "#FAFAFA",
      accent: "#FF4D4D",
      gold: "#FF4D4D",
      text: "#111",
      muted: "#777",
      border: "#E5E5E5",
    },
  },
  {
    id: "forest-natural",
    name: "Doğal Orman",
    desc: "Yeşil, organik doğal his",
    colors: ["#2D4A2B", "#6B8F3C", "#B8A44C", "#F8FAF5"],
    tags: ["Doğal", "Eko"],
    palette: {
      brand: "#2D4A2B",
      warm: "#F8FAF5",
      accent: "#6B8F3C",
      gold: "#B8A44C",
      text: "#2D3B2A",
      muted: "#6B7A62",
      border: "#D8E5D0",
    },
  },
  {
    id: "cream-elegant",
    name: "Krem Elegant",
    desc: "Krem bordo, sofistike",
    colors: ["#5C1A33", "#8B3A5C", "#C4956A", "#FDF9F4"],
    tags: ["Elegant", "Sofistike"],
    palette: {
      brand: "#5C1A33",
      warm: "#FDF9F4",
      accent: "#8B3A5C",
      gold: "#C4956A",
      text: "#3A2030",
      muted: "#8A7A70",
      border: "#E8DDD5",
    },
  },
];

export function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}
