export interface ThemePalette {
  brand: string;
  warm: string;
  accent: string;
  gold: string;
  text: string;
  muted: string;
  border: string;
}

export interface Theme {
  id: string;
  name: string;
  desc: string;
  colors: string[];
  tags: string[];
  sectors: string[];
  palette: ThemePalette;
  fonts?: { heading: string; body: string };
}

export const THEMES: Theme[] = [
  {
    id: "classic-warm",
    name: "Klasik Sıcak",
    desc: "Kahverengi, geleneksel mobilya",
    colors: ["#2C2420", "#C8553D", "#D4A03C", "#FAF8F5"],
    tags: ["Geleneksel", "Sıcak"],
    sectors: ["mobilyaci", "kuyumcu", "cafe", "tanitim", "restoran", "kuafor"],
    palette: {
      brand: "#2C2420",
      warm: "#FAF8F5",
      accent: "#C8553D",
      gold: "#D4A03C",
      text: "#2C2420",
      muted: "#6B5B4E",
      border: "#E8DDD0",
    },
  },
  {
    id: "navy-gold",
    name: "Navy Premium",
    desc: "Lacivert + altın, lüks düğün",
    colors: ["#1B2A4A", "#C9A55C", "#B8464B", "#FFFDF8"],
    tags: ["Premium", "Lüks"],
    sectors: ["mobilyaci", "kuyumcu", "oto-galeri", "tanitim", "portfolyo"],
    palette: {
      brand: "#1B2A4A",
      warm: "#FFFDF8",
      accent: "#C9A55C",
      gold: "#C9A55C",
      text: "#1B2A4A",
      muted: "#7A7062",
      border: "#E5DDD0",
    },
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    desc: "Siyah-beyaz, temiz şık",
    colors: ["#111", "#FF4D4D", "#333", "#FAFAFA"],
    tags: ["Modern", "Minimal"],
    sectors: ["mobilyaci", "kuyumcu", "cafe", "oto-galeri", "tanitim", "restoran", "portfolyo", "kuafor"],
    palette: {
      brand: "#111",
      warm: "#FAFAFA",
      accent: "#FF4D4D",
      gold: "#FF4D4D",
      text: "#111",
      muted: "#777",
      border: "#E5E5E5",
    },
  },
  {
    id: "forest-natural",
    name: "Doğal Orman",
    desc: "Yeşil, organik doğal his",
    colors: ["#2D4A2B", "#6B8F3C", "#B8A44C", "#F8FAF5"],
    tags: ["Doğal", "Eko"],
    sectors: ["mobilyaci", "cafe", "restoran"],
    palette: {
      brand: "#2D4A2B",
      warm: "#F8FAF5",
      accent: "#6B8F3C",
      gold: "#B8A44C",
      text: "#2D3B2A",
      muted: "#6B7A62",
      border: "#D8E5D0",
    },
  },
  {
    id: "cream-elegant",
    name: "Krem Elegant",
    desc: "Krem bordo, sofistike",
    colors: ["#5C1A33", "#8B3A5C", "#C4956A", "#FDF9F4"],
    tags: ["Elegant", "Sofistike"],
    sectors: ["mobilyaci", "kuyumcu", "cafe", "tanitim", "kuafor", "portfolyo"],
    palette: {
      brand: "#5C1A33",
      warm: "#FDF9F4",
      accent: "#8B3A5C",
      gold: "#C4956A",
      text: "#3A2030",
      muted: "#8A7A70",
      border: "#E8DDD5",
    },
  },
  // New sector-specific themes
  {
    id: "cafe-cozy",
    name: "Cafe Sıcak",
    desc: "Kahve tonları, sıcak atmosfer",
    colors: ["#3E2723", "#8D6E63", "#FF8F00", "#FFF8E1"],
    tags: ["Cafe", "Sıcak"],
    sectors: ["cafe", "restoran"],
    palette: {
      brand: "#3E2723",
      warm: "#FFF8E1",
      accent: "#FF8F00",
      gold: "#FF8F00",
      text: "#3E2723",
      muted: "#8D6E63",
      border: "#D7CCC8",
    },
    fonts: { heading: "Playfair Display", body: "DM Sans" },
  },
  {
    id: "auto-dark",
    name: "Auto Koyu",
    desc: "Koyu tema, sportif oto galeri",
    colors: ["#0D1117", "#58A6FF", "#F78166", "#F0F6FC"],
    tags: ["Koyu", "Sportif"],
    sectors: ["oto-galeri"],
    palette: {
      brand: "#0D1117",
      warm: "#F0F6FC",
      accent: "#58A6FF",
      gold: "#F78166",
      text: "#0D1117",
      muted: "#8B949E",
      border: "#30363D",
    },
    fonts: { heading: "DM Sans", body: "DM Sans" },
  },
  {
    id: "jewel-sparkle",
    name: "Mücevher Işıltı",
    desc: "Altın ve siyah, lüks kuyumcu",
    colors: ["#1A1A2E", "#D4AF37", "#C0392B", "#FAF3E0"],
    tags: ["Lüks", "Işıltılı"],
    sectors: ["kuyumcu"],
    palette: {
      brand: "#1A1A2E",
      warm: "#FAF3E0",
      accent: "#D4AF37",
      gold: "#D4AF37",
      text: "#1A1A2E",
      muted: "#7F8C8D",
      border: "#E8D5B5",
    },
    fonts: { heading: "Playfair Display", body: "DM Sans" },
  },
  {
    id: "business-blue",
    name: "Kurumsal Mavi",
    desc: "Profesyonel mavi tonlar, kurumsal",
    colors: ["#1E3A5F", "#3B82F6", "#60A5FA", "#F8FAFC"],
    tags: ["Kurumsal", "Profesyonel"],
    sectors: ["tanitim", "portfolyo"],
    palette: {
      brand: "#1E3A5F",
      warm: "#F8FAFC",
      accent: "#3B82F6",
      gold: "#60A5FA",
      text: "#1E293B",
      muted: "#64748B",
      border: "#E2E8F0",
    },
    fonts: { heading: "DM Sans", body: "DM Sans" },
  },
  {
    id: "salon-chic",
    name: "Salon Şık",
    desc: "Pastel pembe, güzellik salonu",
    colors: ["#4A2040", "#C084FC", "#F9A8D4", "#FDF4FF"],
    tags: ["Şık", "Feminen"],
    sectors: ["kuafor"],
    palette: {
      brand: "#4A2040",
      warm: "#FDF4FF",
      accent: "#C084FC",
      gold: "#F9A8D4",
      text: "#3B1F35",
      muted: "#9C8899",
      border: "#F0D9E8",
    },
    fonts: { heading: "Playfair Display", body: "DM Sans" },
  },
  // ── Yeni temalar ──────────────────────────────────
  {
    id: "sunset-terracotta",
    name: "Gün Batımı",
    desc: "Terracotta ve turuncu, sıcak Akdeniz",
    colors: ["#92400E", "#D97706", "#F59E0B", "#FFFBEB"],
    tags: ["Sıcak", "Akdeniz"],
    sectors: ["mobilyaci", "cafe", "restoran", "kuafor"],
    palette: {
      brand: "#92400E",
      warm: "#FFFBEB",
      accent: "#D97706",
      gold: "#F59E0B",
      text: "#78350F",
      muted: "#A8896C",
      border: "#FDE68A",
    },
    fonts: { heading: "Playfair Display", body: "DM Sans" },
  },
  {
    id: "ocean-breeze",
    name: "Okyanus Esintisi",
    desc: "Turkuaz ve mavi, ferah deniz",
    colors: ["#0E4D64", "#0891B2", "#22D3EE", "#ECFEFF"],
    tags: ["Ferah", "Deniz"],
    sectors: ["cafe", "restoran", "tanitim", "portfolyo", "kuafor"],
    palette: {
      brand: "#0E4D64",
      warm: "#ECFEFF",
      accent: "#0891B2",
      gold: "#22D3EE",
      text: "#164E63",
      muted: "#6B8A94",
      border: "#A5F3FC",
    },
    fonts: { heading: "DM Sans", body: "DM Sans" },
  },
  {
    id: "midnight-luxe",
    name: "Gece Lüks",
    desc: "Koyu mor ve altın, premium gece",
    colors: ["#1E1035", "#7C3AED", "#A78BFA", "#FAF5FF"],
    tags: ["Lüks", "Gece"],
    sectors: ["kuyumcu", "kuafor", "portfolyo", "oto-galeri"],
    palette: {
      brand: "#1E1035",
      warm: "#FAF5FF",
      accent: "#7C3AED",
      gold: "#A78BFA",
      text: "#2E1065",
      muted: "#7C6F9B",
      border: "#DDD6FE",
    },
    fonts: { heading: "Playfair Display", body: "DM Sans" },
  },
  {
    id: "rose-garden",
    name: "Gül Bahçesi",
    desc: "Pembe ve gül, romantik zarif",
    colors: ["#881337", "#E11D48", "#FB7185", "#FFF1F2"],
    tags: ["Romantik", "Zarif"],
    sectors: ["kuafor", "kuyumcu", "cafe"],
    palette: {
      brand: "#881337",
      warm: "#FFF1F2",
      accent: "#E11D48",
      gold: "#FB7185",
      text: "#4C0519",
      muted: "#9F7080",
      border: "#FECDD3",
    },
    fonts: { heading: "Playfair Display", body: "DM Sans" },
  },
  {
    id: "slate-corporate",
    name: "Kurumsal Gri",
    desc: "Profesyonel gri tonlar, ciddi iş",
    colors: ["#1E293B", "#475569", "#94A3B8", "#F8FAFC"],
    tags: ["Kurumsal", "Ciddi"],
    sectors: ["tanitim", "portfolyo", "oto-galeri"],
    palette: {
      brand: "#1E293B",
      warm: "#F8FAFC",
      accent: "#475569",
      gold: "#94A3B8",
      text: "#0F172A",
      muted: "#64748B",
      border: "#CBD5E1",
    },
    fonts: { heading: "DM Sans", body: "DM Sans" },
  },
  {
    id: "emerald-fresh",
    name: "Zümrüt Taze",
    desc: "Canlı yeşil, enerji dolu",
    colors: ["#064E3B", "#059669", "#34D399", "#ECFDF5"],
    tags: ["Taze", "Enerjik"],
    sectors: ["cafe", "restoran", "tanitim", "kuafor"],
    palette: {
      brand: "#064E3B",
      warm: "#ECFDF5",
      accent: "#059669",
      gold: "#34D399",
      text: "#022C22",
      muted: "#5E8A7A",
      border: "#A7F3D0",
    },
    fonts: { heading: "DM Sans", body: "DM Sans" },
  },
  {
    id: "cherry-bold",
    name: "Kiraz Cesur",
    desc: "Kırmızı ve siyah, cesur dikkat çekici",
    colors: ["#1A0000", "#DC2626", "#EF4444", "#FEF2F2"],
    tags: ["Cesur", "Dikkat Çekici"],
    sectors: ["oto-galeri", "mobilyaci", "restoran", "portfolyo"],
    palette: {
      brand: "#1A0000",
      warm: "#FEF2F2",
      accent: "#DC2626",
      gold: "#EF4444",
      text: "#1A0000",
      muted: "#8B6060",
      border: "#FECACA",
    },
    fonts: { heading: "DM Sans", body: "DM Sans" },
  },
  {
    id: "honey-warm",
    name: "Bal Sıcaklığı",
    desc: "Bal ve amber, davetkar sıcak",
    colors: ["#451A03", "#B45309", "#F59E0B", "#FFFBEB"],
    tags: ["Davetkar", "Sıcak"],
    sectors: ["mobilyaci", "cafe", "restoran", "kuafor", "tanitim"],
    palette: {
      brand: "#451A03",
      warm: "#FFFBEB",
      accent: "#B45309",
      gold: "#F59E0B",
      text: "#451A03",
      muted: "#92700A",
      border: "#FDE68A",
    },
    fonts: { heading: "Playfair Display", body: "DM Sans" },
  },
];

export function getThemeById(id: string): Theme {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}

export function getThemesBySector(sectorId: string): Theme[] {
  return THEMES.filter((t) => t.sectors.includes(sectorId));
}
